### ISSUE TITLE
Unhandled exception with impersonation

### ISSUE THREAD

**Issue by asserjunnila** [FrendsPlatform/Frends.Files#27]
The issue remains from Frends.File:

https://github.com/FrendsPlatform/Frends.File/issues/14 

TL;DR: "Use given user credentials for remote connections" does not work when targeting core or standard.

**Comment by RikuVirtanen** [comment]
This has been fixed with updating the SimpleImpersonation library. Now this feature is compatible on .NET6. However, like the old version, SimpleImpersonation is only supported on Windows. This means that It's not a Crossplatform feature.
