### ISSUE TITLE
Frends.Files.LocalBackup could use macros in Backup directory input field

### ISSUE THREAD

**Issue by RikuVirtanen** [FrendsPlatform/Frends.Files#5]
Macros could be implemented in the backup directory. This could be done by following how the macros are handled in Frends.SFTP https://github.com/FrendsPlatform/Frends.SFTP or Frends.FTP https://github.com/FrendsPlatform/Frends.FTP tasks or in Cobalt https://github.com/FrendsPlatform/Frends.Cobalt.

**Comment by jefim** [comment]
Let's not implement this just yet, unless  we get a good use case for it. At the moment the case was to use dates in backup dir, which is 
1) dangerous, since cleanup won't clean those folders up as they are dynamic and 
2) you can achieve the same using smth lie DateTime.Today.Year and such.
