### ISSUE TITLE
netstandard2.0;net4xx support possible?

### ISSUE THREAD

**Issue by jsalmela** [FrendsPlatform/Frends.Files#50]
Hi,

Is there some technical reason why all these tasks are net6.0 only? If you could add at least .netstandard2.0 support it would make the migration from old tasks to these the much easier. Of course if possible add net4 Framework support too.

**Comment by jefim** [comment]
Hello, these are tasks specifically created for newer Frends versions. There are no plans to make this net standard 2.0 compatible or framework compatible.

For .NET Standard 2.0 and Framework 4.7.1 tasks use Frends.File tasks here - https://github.com/FrendsPlatform/Frends.File.
