### ISSUE TITLE
Files.Write encode ANSI does not work on NET6 and 8

### ISSUE THREAD

**Issue by helvertti** [FrendsPlatform/Frends.Files#66]
"Encoding.Default" which the task uses for encoding the ANSI files has unexpected behavior on NET6 and 8 processes. The default uses UTF-8 on those frameworks: https://thebuildingcoder.typepad.com/blog/2024/04/migrating-from-net-48-to-net-core-8.html

Using "iso-8859-1" encoding worked instead.

**Comment by RikuVirtanen** [comment]
ANSI refers to the default encoding of the machine. Earlier the default encoding has been windows-1252 in older machines, but nowadays it's most likely an UTF-8 encoding. We can change the naming of that parameter to be default but other than that this is not a bug.
