### ISSUE TITLE
LocalBackup: Files are transfered to sub-directory, not in backup directory

### ISSUE THREAD

**Issue by Svenskapojkarna** [FrendsPlatform/Frends.Files#7]
Check comments too
---

Task will create backup folder automatically with predefined name. There has been reports that this is not a working solution, since they want to have all backups under same directory without any random sub-directories.

Basically if you define the directory as `C:\tmp\archive`, then the files should be at `C:\tmp\archive`, not in `C:\tmp\archive\{timestamp}-{Guid}`.

As implementation proposal the task should always save the files to the given directory. There could also be a boolean where user can select to create directory if the directory does not exist.

**Comment by jefim** [comment]
Let's introduce a boolean "Create subdirectories", true by default. Make sure to check cleanup code knows that it needs to check last access or last modified date for the file (check from Cobalt).

Also remember to update documentation and how this setting affects cleanup procedure.
